---
name: ci

"on":
  pull_request:
    branches:
      - master
      - main
      - develop
  push:
    branches:
      - master
      - main
      - develop
env:
  debug_ci: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run make test
        run: |
          bundle exec make test
  bootstrap:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Add --no-document to .gemrc
        run: |
          tee -a $HOME/.gemrc <<EOGEMRC
          install: --no-document
          update: --no-document
          EOGEMRC
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add SSH_AUTH_SOCK to root shell .profile
        run: |
          sudo tee -a ~root/.profile <<EOPROFILE
          SSH_AUTH_SOCK=${{ env.SSH_AUTH_SOCK }}
          EOPROFILE
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 1
      - name: Set BREWFILE_PATH env var
        run: |
          echo "BREWFILE_PATH=${GITHUB_WORKSPACE}/test/fixtures/tmp/Brewfile.ci" >> $GITHUB_ENV
      - name: Debug GitHub Cache Paths BREWFILE_PATH
        run: |
          echo BREWFILE_PATH=$BREWFILE_PATH
          echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
      - name: DEBUG - Print all shell env exports
        run: export -p
        if: env.debug_ci
      - name: DEBUG - List workspace and Homebrew contents
        run: |
          ls -lR ${GITHUB_WORKSPACE}
          ls -lR /usr/local/Homebrew
        if: env.debug_ci
      - name: Generate Brewfile from soloistrc test fixture
        run: make brewfile
      - name: Configure Homebrew cache
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/Homebrew/*--*
            ~/Library/Caches/Homebrew/downloads/*--*
            ~/Library/Caches/Homebrew/Cask/*--*
            /usr/local/Homebrew/Library/Taps/**
            /opt/Homebrew/Library/Taps/**
            ./Brewfile.lock.json
          key: brew-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles( env.BREWFILE_PATH, '**/Brewfile.lock.json') }}
          restore-keys: |
            brew-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles( env.BREWFILE_PATH, '**/Brewfile.lock.json') }}
            brew-${{ runner.os }}-${{ runner.arch }}-
            brew-${{ runner.os }}-
      - name: Re-enable checksum offloading
        # See: https://github.com/actions/virtual-environments/issues/1187#issuecomment-696195756
        run: |
          sudo sysctl -w net.link.generic.system.hwcksum_tx=1
          sudo sysctl -w net.link.generic.system.hwcksum_rx=1
      - name: Run bootstrap.sh + soloist with test fixtures
        run: |
          make bootstrap
